<?php
$data=$block->_prepareLayout();
$checked_male=null;
$checked_female=null;
$submit=null;
if($data[3]=="Male")
		$checked_male="checked";
else if($data[3]=="Female")
		$checked_female="checked";
	
if($data)
	$submit="Update";
else
	$submit="Add Row";
?>

<!DOCTYPE html>
<html>
<head>
	<title>Add/Delete/Edit Database</title>
</head>
<body>

<center>
   <form method="post" action="world">
    <input type="hidden" name="id" value="<?php if($data) ?>" />
	<label>Name</label><input type="text" name="name" value="<?php if($data)echo $data[0];?>" required/><br><br>
	<label>Email</label><input type="email" name="email" value="<?php if($data) echo $data[1]; ?>" /><br><br>
	<label>Mobile Number</label><input type="number" name="number" value="<?php if($data) echo $data[2];?>" /><br><br>
	<label id="gender">Gender</label><input type="radio" name="g" value="Male" <?php echo $checked_male;?>/>
	<label>Male</label><input type="radio" name="g" value="Female" <?php echo $checked_female;?>/><label>Female</label><br><br>

	<input type="submit" name="add" value="<?php echo $submit;?>"/>
   </form>
</center>
</body>
</html>
